repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: license-checker
        name: license checker
        entry: python3 license_checker.py
        language: python
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        always_run: true
        pass_filenames: false